apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: racingcaranimation
  namespace: hml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: racingcaranimation
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
