kind: Service
apiVersion: v1
metadata:
  name: racingcaranimation
  namespace: hml
spec:
  selector:
    app: racingcaranimation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    #nodePort: 30080
  #type: NodePort
