apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simplewhale
  namespace: hml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simplewhale
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50  
